sudo: false
language: node_js
node_js:
  - '0.12'
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_deploy:
  - npm run archive
deploy:
  provider: releases
  api_key:
    secure: ag2ObhNaZYbULIABDARbHyvqk9DChYg6j6HZUmocdfM4Go/MF/OckpR0VntiMKpv+eQ8vdmTyRWVcW4Y/B+AOkMs/fhRs4rYOLq7BXWyLLbcvNaXP+3n6HDB/RZBPcNCYdQUo+oDDOyk7W9vF5T3o4aKlXFRLQIVQgABrwEQC1I=
  file: build/openlayers-workshop.zip
  on:
    repo: openlayers/workshop
    tags: true
